version: '3.8'

services:
  # 1. Serviço do Banco de Dados MySQL
  mysql-db:
    image: mysql:8.0.39 # Imagem oficial do MySQL
    container_name: mysql-db # Nome do contêiner
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appfolha
    ports:
      - 3306:3306 # Mapeia a porta 3306 do contêiner para a 3306 da sua máquina (opcional)
    volumes:
      - mysql_data:/var/lib/mysql # Persistência de dados

  backend-java:
    build:
      context: . # Constrói a imagem a partir do Dockerfile neste diretório
      dockerfile: ./dockerfiles/java.Dockerfile
    container_name: backend-java-container # Nome do contêiner

    ports:
      - 8080:8080
    depends_on:
      - mysql-db # Garante que o MySQL inicie antes da aplicação Java
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/appfolha?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  # 3. Serviço do Frontend Angular
  frontend-angular:
    build:
      context: . # Pasta onde está o Dockerfile do Angular
      dockerfile: ./dockerfiles/angular.Dockerfile # Pode usar um Dockerfile para produção
    container_name: frontend-angular-container
    ports:
      - 4200:80 # Mapeia a porta do Nginx (80) para a porta do host (4200, por exemplo)
    restart: always
    depends_on:
      - backend-java # Opcional, mas ajuda a garantir a ordem de inicialização

volumes:
  mysql_data: # Define o volume de persistência para o MySQL

networks:
  default:
    driver: bridge