version: '3.8'

services:
  # 1. Serviço do Banco de Dados MySQL
  mysql-db:
    image: mysql:8.0.39 # Imagem oficial do MySQL
    container_name: mysql-db # Nome do contêiner
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appfolha
    ports:
      - 3306:3306 # Mapeia a porta 3306 do contêiner para a 3306 da sua máquina (opcional)
    volumes:
      - mysql_data:/var/lib/mysql # Persistência de dados

  backend-java:
    build:
      context: . # Constrói a imagem a partir do Dockerfile neste diretório
      dockerfile: ./dockerfiles/java.Dockerfile
    container_name: backend-java-container # Nome do contêiner

    ports:
      - 8080:8080
    depends_on:
      - mysql-db # Garante que o MySQL inicie antes da aplicação Java
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/appfolha?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root


volumes:
  mysql_data: # Define o volume de persistência para o MySQL

networks:
  default:
    driver: bridge